<a href="https://colab.research.google.com/github/fegasu/python/blob/master/cnxsqlite.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Conectando Python con Sqlite
Por Jose Fernando Galindo<br>
Ingrese a la pagina:
https://colab.research.google.com/<br>
Descargue la base de datos Neptuno.sqlite en:<br>
http://fegasusoft.com/innca/sql/movil/tool.htm

Establezco la conexión a sqlite

In [ ]:
import  sqlite3
import pandas as pd
con = sqlite3.connect('Neptuno.sqlite')
cursorObj = con.cursor()

# Sección nueva

Ejecutar una sentencia SELECT

In [ ]:
query='SELECT * FROM clientes'
#df = pd.read_sql_query(query, con)
#df=list(df)
cursorObj.execute(query)

OperationalError: ignored

# Nueva sección

Cuantas filas tiene la tabla

In [ ]:
rows = cursorObj.fetchall()
print(len(rows))

68

Muestra las columnas de la consulta

In [ ]:
 for i in df:
    print(i)

Idcliente
Nombrecompania
Nombrecontacto
Cargocontacto
Direccion
Ciudad
Region
Codigopostal
Pais
Telefono
Fax

Despliega las filas de la tabla

In [ ]:
# for row in rows: 
#         print(row)
rows

[('ALFKI',
  'Alfreds Futterkiste',
  'Maria Anders',
  'Representante de ventas',
  'Obere Str. 57',
  'Berlín',
  None,
  '12209',
  'Alemania',
  '030-0074321',
  '030-0076545'),
 ('ANATR',
  'Ana Trujillo Emparedados y helados',
  'Ana Trujillo',
  'Propietario',
  'Avda. de la Constitución 2222',
  'México D.F.',
  None,
  '05021',
  'México',
  '(5) 555-4729',
  '(5) 555-3745'),
 ('ANTON',
  'Antonio Moreno Taquería',
  'Antonio Moreno',
  'Propietario',
  'Mataderos  2312',
  'México D.F.',
  None,
  '05023',
  'México',
  '(5) 555-3932',
  None),
 ('AROUT',
  'Around the Horn',
  'Thomas Hardy',
  'Representante de ventas',
  '120 Hanover Sq.',
  'Londres',
  None,
  'WA1 1DP',
  'Reino Unido ',
  '(71) 555-7788',
  '(71) 555-6750'),
 ('BERGS',
  'Berglunds snabbköp',
  'Christina Berglund',
  'Administrador de pedidos',
  'Berguvsvägen  8',
  'Luleå',
  None,
  'S-958 22',
  'Suecia',
  '0921-12 34 65',
  '0921-12 34 67'),
 ('BLAUS',
  'Blauer See Delikatessen',
  'Hanna Moos',
  'Representante de ventas',
  'Forsterstr. 57',
  'Mannheim',
  None,
  '68306',
  'Alemania',
  '0621-08460',
  '0621-08924'),
 ('BLONP',
  'Blondel père et fils',
  'Frédérique Citeaux',
  'Gerente de marketing',
  '24, place Kléber',
  'Estrasburgo',
  None,
  '67000',
  'Francia',
  '88.60.15.31',
  '88.60.15.32'),
 ('BOLID',
  'Bólido Comidas preparadas',
  'Martín Sommer',
  'Propietario',
  'C/ Araquil, 67',
  'Madrid',
  None,
  '28023',
  'España',
  '(91) 555 22 82',
  '(91) 555 91 99'),
 ('BONAP',
  "Bon app'",
  'Laurence Lebihan',
  'Propietario',
  '12, rue des Bouchers',
  'Marsella',
  None,
  '13008',
  'Francia',
  '91.24.45.40',
  '91.24.45.41'),
 ('BSBEV',
  "B's Beverages",
  'Victoria Ashworth',
  'Representante de ventas',
  'Fauntleroy Circus',
  'Londres',
  None,
  'EC2 5NT',
  'Reino Unido',
  '(71) 555-1212',
  None),
 ('CACTU',
  'Cactus Comidas para llevar',
  'Patricio Simpson',
  'Agente de ventas',
  'Cerrito 333',
  'Buenos Aires',
  None,
  '1010',
  'Argentina',
  '(1) 135-5555',
  '(1) 135-4892'),
 ('CENTC',
  'Centro comercial Moctezuma',
  'Francisco Chang',
  'Gerente de marketing',
  'Sierras de Granada 9993',
  'México D.F.',
  None,
  '05022',
  'México',
  '(5) 555-3392',
  '(5) 555-7293'),
 ('CHOPS',
  'Chop-suey Chinese',
  'Yang Wang',
  'Propietario',
  'Hauptstr. 29',
  'Berna',
  None,
  '3012',
  'Suiza',
  '0452-076545',
  None),
 ('COMMI',
  'Comércio Mineiro',
  'Pedro Afonso',
  'Asistente de ventas',
  'Av. dos Lusíadas, 23',
  'São Paulo',
  'SP',
  '05432-043',
  'Brasil',
  '(11) 555-7647',
  None),
 ('DRACD',
  'Drachenblut Delikatessen',
  'Sven Ottlieb',
  'Administrador de pedidos',
  'Walserweg 21',
  'Aachen',
  None,
  '52066',
  'Alemania',
  '0241-039123',
  '0241-059428'),
 ('DUMON',
  'Du monde entier',
  'Janine Labrune',
  'Propietario',
  '67, rue des Cinquante Otages',
  'Nantes',
  None,
  '44000',
  'Francia',
  '40.67.88.88',
  '40.67.89.89'),
 ('EASTC',
  'Eastern Connection',
  'Ann Devon',
  'Agente de ventas',
  '35 King George',
  'Londres',
  None,
  'WX3 6FW',
  'Reino Unido',
  '(71) 555-0297',
  '(71) 555-3373'),
 ('ERNSH',
  'Ernst Handel',
  'Roland Mendel',
  'Gerente de ventas',
  'Kirchgasse 6',
  'Graz',
  None,
  '8010',
  'Austria',
  '7675-3425',
  '7675-3426'),
 ('FAMIA',
  'Familia Arquibaldo',
  'Aria Cruz',
  'Asistente de marketing',
  'Rua Orós, 92',
  'Sao Paulo',
  'SP',
  '05442-030',
  'Brasil',
  '(11) 555-9857',
  None),
 ('FISSA',
  'FISSA Fabrica Inter. Salchichas S.A.',
  'Diego Roel',
  'Gerente de contabilidad',
  'C/ Moralzarzal, 86',
  'Madrid',
  None,
  '28034',
  'España',
  '(91) 555 94 44',
  '(91) 555 55 93'),
 ('FOLKO',
  'Folk och fä HB',
  'Maria Larsson',
  'Propietario',
  'Åkergatan 24',
  'Bräcke',
  None,
  'S-844 67',
  'Suecia',
  '0695-34 67 21',
  None),
 ('FRANK',
  'Frankenversand',
  'Peter Franken',
  'Gerente de marketing',
  'Berliner Platz 43',
  'München',
  None,
  '80805',
  'Alemania',
  '089-0877310',
  '089-0877451'),
 ('FRANR',
  'France restauration',
  'Carine Schmitt',
  'Gerente de marketing',
  '54, rue Royale',
  'Nantes',
  None,
  '44000',
  'Francia',
  '40.32.21.21',
  '40.32.21.20'),
 ('FRANS',
  'Franchi S.p.A.',
  'Paolo Accorti',
  'Representante de ventas',
  'Via Monte Bianco 34',
  'Torino',
  None,
  '10100',
  'Italia',
  '011-4988260',
  '011-4988261'),
 ('FURIB',
  'Furia Bacalhau e Frutos do Mar',
  'Lino Rodriguez ',
  'Gerente de ventas',
  'Jardim das rosas n. 32',
  'Lisboa',
  None,
  '1675',
  'Portugal',
  '(1) 354-2534',
  '(1) 354-2535'),
 ('GALED',
  'Galería del gastrónomo',
  'Eduardo Saavedra',
  'Gerente de marketing',
  'Rambla de Cataluña, 23',
  'Barcelona',
  None,
  '08022',
  'España',
  '(93) 203 4560',
  '(93) 203 4561'),
 ('GODOS',
  'Godos Cocina Típica',
  'José Pedro Freyre',
  'Gerente de ventas',
  'C/ Romero, 33',
  'Sevilla',
  None,
  '41101',
  'España',
  '(95) 555 82 82',
  None),
 ('GOURL',
  'Gourmet Lanchonetes',
  'André Fonseca',
  'Asistente de ventas',
  'Av. Brasil, 442',
  'Campinas',
  'SP',
  '04876-786',
  'Brasil',
  '(11) 555-9482',
  None),
 ('GREAL',
  'Great Lakes Food Market',
  'Howard Snyder',
  'Gerente de marketing',
  '2732 Baker Blvd.',
  'Eugenia',
  'OR',
  '97403',
  'Estados Unidos',
  '(503) 555-7555',
  None),
 ('GROSR',
  'GROSELLA-Restaurante',
  'Manuel Pereira',
  'Propietario',
  '5ª Ave. Los Palos Grandes',
  'Caracas',
  'DF',
  '1081',
  'Venezuela',
  '(2) 283-2951',
  '(2) 283-3397'),
 ('HANAR',
  'Hanari Carnes',
  'Mario Pontes',
  'Gerente de contabilidad',
  'Rua do Paço, 67',
  'Rio de Janeiro',
  'RJ',
  '05454-876',
  'Brasil',
  '(21) 555-0091',
  '(21) 555-8765'),
 ('HILAA',
  'HILARIÓN-Abastos',
  'Carlos Hernández',
  'Representante de ventas',
  'Carrera 22 con Ave. Carlos Soublette #8-35',
  'San Cristóbal',
  'Táchira',
  '5022',
  'Venezuela',
  '(5) 555-1340',
  '(5) 555-1948'),
 ('HUNGO',
  'Hungry Owl All-Night Grocers',
  'Patricia McKenna',
  'Asistente de ventas',
  '8 Johnstown Road',
  'Cork',
  'Co. Cork',
  None,
  'Irlanda',
  '2967 542',
  '2967 3333'),
 ('KOENE',
  'Königlich Essen',
  'Philip Cramer',
  'Asistente de ventas',
  'Maubelstr. 90',
  'Brandenburgo',
  None,
  '14776',
  'Alemania',
  '0555-09876',
  None),
 ('LACOR',
  "La corne d'abondance",
  'Daniel Tonini',
  'Representante de ventas',
  "67, avenue de l'Europe",
  'Versalles',
  None,
  '78000',
  'Francia',
  '30.59.84.10',
  '30.59.85.11'),
 ('LAMAI',
  "La maison d'Asie",
  'Annette Roulet',
  'Gerente de ventas',
  '1 rue Alsace-Lorraine',
  'Toulouse',
  None,
  '31000',
  'Francia',
  '61.77.61.10',
  '61.77.61.11'),
 ('LEHMS',
  'Lehmanns Marktstand',
  'Renate Messner',
  'Representante de ventas',
  'Magazinweg 7',
  'Francfurt',
  None,
  '60528',
  'Alemania',
  '069-0245984',
  '069-0245874'),
 ('LILAS',
  'LILA-Supermercado',
  'Carlos González',
  'Gerente de contabilidad',
  'Carrera 52 con Ave. Bolívar #65-98 Llano Largo',
  'Barquisimeto',
  'Lara',
  '3508',
  'Venezuela',
  '(9) 331-6954',
  '(9) 331-7256'),
 ('MAGAA',
  'Magazzini Alimentari Riuniti',
  'Giovanni Rovelli',
  'Gerente de marketing',
  'Via Ludovico il Moro 22',
  'Bérgamo',
  None,
  '24100',
  'Italia',
  '035-640230',
  '035-640231'),
 ('MAISD',
  'Maison Dewey',
  'Catherine Dewey',
  'Agente de ventas',
  'Rue Joseph-Bens 532',
  'Bruselas',
  None,
  'B-1180',
  'Bélgica',
  '(02) 201 24 67',
  '(02) 201 24 68'),
 ('MORGK',
  'Morgenstern Gesundkost',
  'Alexander Feuer',
  'Asistente de marketing',
  'Heerstr. 22',
  'Leipzig',
  None,
  '04179',
  'Alemania',
  '0342-023176',
  None),
 ('NORTS',
  'North/South',
  'Simon Crowther',
  'Asistente de ventas',
  'South House 300 Queensbridge',
  'Londres',
  None,
  'SW7 1RZ',
  'Reino Unido',
  '(71) 555-7733',
  '(71) 555-2530'),
 ('OCEAN',
  'Océano Atlántico Ltda.',
  'Yvonne Moncada',
  'Agente de ventas',
  'Ing. Gustavo Moncada 8585 Piso 20-A',
  'Buenos Aires',
  None,
  '1010',
  'Argentina',
  '(1) 135-5333',
  '(1) 135-5535'),
 ('OTTIK',
  'Ottilies Käseladen',
  'Henriette Pfalzheim',
  'Propietario',
  'Mehrheimerstr. 369',
  'Köln',
  None,
  '50739',
  'Alemania',
  '0221-0644327',
  '0221-0765721'),
 ('PERIC',
  'Pericles Comidas clásicas',
  'Guillermo Fernández',
  'Representante de ventas',
  'Calle Dr. Jorge Cash 321',
  'México D.F.',
  None,
  '05033',
  'México',
  '(5) 552-3745',
  '(5) 545-3745'),
 ('PICCO',
  'Piccolo und mehr',
  'Georg Pipps',
  'Gerente de ventas',
  'Geislweg 14',
  'Salzburgo',
  None,
  '5020',
  'Austria',
  '6562-9722',
  '6562-9723'),
 ('PRINI',
  'Princesa Isabel Vinhos',
  'Isabel de Castro',
  'Representante de ventas',
  'Estrada da saúde n. 58',
  'Lisboa',
  None,
  '1756',
  'Portugal',
  '(1) 356-5634',
  None),
 ('QUEDE',
  'Que Delícia',
  'Bernardo Batista',
  'Gerente de contabilidad',
  'Rua da Panificadora, 12',
  'Rio de Janeiro',
  'RJ',
  '02389-673',
  'Brasil',
  '(21) 555-4252',
  '(21) 555-4545'),
 ('QUEEN',
  'Queen Cozinha',
  'Lúcia Carvalho',
  'Asistente de marketing',
  'Alameda dos Canàrios, 891',
  'Sao Paulo',
  'SP',
  '05487-020',
  'Brasil',
  '(11) 555-1189',
  None),
 ('QUICK',
  'QUICK-Stop',
  'Horst Kloss',
  'Gerente de contabilidad',
  'Taucherstraße 10',
  'Cunewalde',
  None,
  '01307',
  'Alemania',
  '0372-035188',
  None),
 ('RANCH',
  'Rancho grande',
  'Sergio Gutiérrez',
  'Representante de ventas',
  'Av. del Libertador 900',
  'Buenos Aires',
  None,
  '1010',
  'Argentina',
  '(1) 123-5555',
  '(1) 123-5556'),
 ('REGGC',
  'Reggiani Caseifici',
  'Maurizio Moroni',
  'Asistente de ventas',
  'Strada Provinciale 124',
  'Reggio Emilia',
  None,
  '42100',
  'Italia',
  '0522-556721',
  '0522-556722'),
 ('RICSU',
  'Richter Supermarkt',
  'Michael Holz',
  'Gerente de ventas',
  'Grenzacherweg 237',
  'Génova',
  None,
  '1203',
  'Suiza',
  '0897-034214',
  None),
 ('ROMEY',
  'Romero y tomillo',
  'Alejandra Camino',
  'Gerente de contabilidad',
  'Gran Vía, 1',
  'Madrid',
  None,
  '28001',
  'España',
  '(91) 745 6200',
  '(91) 745 6210'),
 ('SANTG',
  'Santé Gourmet',
  'Jonas Bergulfsen',
  'Propietario',
  'Erling Skakkes gate 78',
  'Stavern',
  None,
  '4110',
  'Noruega',
  '07-98 92 35',
  '07-98 92 47'),
 ('SAVEA',
  'Save-a-lot Markets',
  'Jose Pavarotti',
  'Representante de ventas',
  '187 Suffolk Ln.',
  'Boise',
  'ID',
  '83720',
  'Estados Unidos',
  '(208) 555-8097',
  None),
 ('SEVES',
  'Seven Seas Imports',
  'Hari Kumar',
  'Gerente de ventas',
  '90 Wadhurst Rd.',
  'Londres',
  None,
  'OX15 4NB',
  'Reino Unido',
  '(71) 555-1717',
  '(71) 555-5646'),
 ('SIMOB',
  'Simons bistro',
  'Jytte Petersen',
  'Propietario',
  'Vinbæltet 34',
  'København',
  None,
  '1734',
  'Dinamarca',
  '31 12 34 56',
  '31 13 35 57'),
 ('TOMSP',
  'Toms Spezialitäten',
  'Karin Josephs',
  'Gerente de marketing',
  'Luisenstr. 48',
  'Münster',
  None,
  '44087',
  'Alemania',
  '0251-031259',
  '0251-035695'),
 ('TORTU',
  'Tortuga Restaurante',
  'Miguel Angel Paolino',
  'Propietario',
  'Avda. Azteca 123',
  'México D.F.',
  None,
  '05033',
  'México',
  '(5) 555-2933',
  None),
 ('TRADH',
  'Tradição Hipermercados',
  'Anabela Domingues',
  'Representante de ventas',
  'Av. Inês de Castro, 414',
  'Sao Paulo',
  'SP',
  '05634-030',
  'Brasil',
  '(11) 555-2167',
  '(11) 555-2168'),
 ('VAFFE',
  'Vaffeljernet',
  'Palle Ibsen',
  'Gerente de ventas',
  'Smagsløget 45',
  'Århus',
  None,
  '8200',
  'Dinamarca',
  '86 21 32 43',
  '86 22 33 44'),
 ('VICTE',
  'Victuailles en stock',
  'Mary Saveley',
  'Agente de ventas',
  '2, rue du Commerce',
  'Lion',
  None,
  '69004',
  'Francia',
  '78.32.54.86',
  '78.32.54.87'),
 ('VINET',
  'Vins et alcools Chevalier',
  'Paul Henriot',
  'Gerente de contabilidad',
  "59 rue de l'Abbaye",
  'Reims',
  None,
  '51100',
  'Francia',
  '26.47.15.10',
  '26.47.15.11'),
 ('WANDK',
  'Die Wandernde Kuh',
  'Rita Müller',
  'Representante de ventas',
  'Adenauerallee 900',
  'Stuttgart',
  None,
  '70563',
  'Alemania',
  '0711-020361',
  '0711-035428'),
 ('WARTH',
  'Wartian Herkku',
  'Pirkko Koskitalo',
  'Gerente de contabilidad',
  'Torikatu 38',
  'Oulu',
  None,
  '90110',
  'Finlandia',
  '981-443655',
  '981-443655'),
 ('WELLI',
  'Wellington Importadora',
  'Paula Parente',
  'Gerente de ventas',
  'Rua do Mercado, 12',
  'Resende',
  'SP',
  '08737-363',
  'Brasil',
  '(14) 555-8122',
  None),
 ('WILMK',
  'Wilman Kala',
  'Matti Karttunen',
  'Prop./Asistente marketing',
  'Keskuskatu 45',
  'Helsinki',
  None,
  '21240',
  'Finlandia',
  '90-224 8858',
  '90-224 8858')]

Despliega la tercera fila

In [ ]:
print(rows[2])
print(rows[0][2])

('ANTON', 'Antonio Moreno Taquería', 'Antonio Moreno', 'Propietario', 'Mataderos  2312', 'México D.F.', None, '05023', 'México', '(5) 555-3932', None)
Maria Anders

Convierte a DataFrame

In [ ]:
import pandas as pd
import numpy as np
a=list(rows)
a=pd.DataFrame(rows)
a

       0                                   1   ...             9              10
0   ALFKI                 Alfreds Futterkiste  ...    030-0074321    030-0076545
1   ANATR  Ana Trujillo Emparedados y helados  ...   (5) 555-4729   (5) 555-3745
2   ANTON             Antonio Moreno Taquería  ...   (5) 555-3932           None
3   AROUT                     Around the Horn  ...  (71) 555-7788  (71) 555-6750
4   BERGS                  Berglunds snabbköp  ...  0921-12 34 65  0921-12 34 67
..    ...                                 ...  ...            ...            ...
63  VINET           Vins et alcools Chevalier  ...    26.47.15.10    26.47.15.11
64  WANDK                   Die Wandernde Kuh  ...    0711-020361    0711-035428
65  WARTH                      Wartian Herkku  ...     981-443655     981-443655
66  WELLI              Wellington Importadora  ...  (14) 555-8122           None
67  WILMK                         Wilman Kala  ...    90-224 8858    90-224 8858

[68 rows x 11 columns]

Renombrar las columnas del DataFrame

In [ ]:
# a=a.rename(columns={0:"id",1:"idcategoria",2:"Nombrecategoria",3:"Descripcion"})

for i in range(len(df)):
  a=a.rename(columns={i:df[i]})
  
a

   Idcliente                      Nombrecompania  ...       Telefono            Fax
0      ALFKI                 Alfreds Futterkiste  ...    030-0074321    030-0076545
1      ANATR  Ana Trujillo Emparedados y helados  ...   (5) 555-4729   (5) 555-3745
2      ANTON             Antonio Moreno Taquería  ...   (5) 555-3932           None
3      AROUT                     Around the Horn  ...  (71) 555-7788  (71) 555-6750
4      BERGS                  Berglunds snabbköp  ...  0921-12 34 65  0921-12 34 67
..       ...                                 ...  ...            ...            ...
63     VINET           Vins et alcools Chevalier  ...    26.47.15.10    26.47.15.11
64     WANDK                   Die Wandernde Kuh  ...    0711-020361    0711-035428
65     WARTH                      Wartian Herkku  ...     981-443655     981-443655
66     WELLI              Wellington Importadora  ...  (14) 555-8122           None
67     WILMK                         Wilman Kala  ...    90-224 8858    90-224 8858

[68 rows x 11 columns]

Duplica una tabla

In [ ]:
from sqlite3 import Error
try:
  query='create table prueba as select * from categorias'
  cursorObj.execute(query)
except Error:
  print(Error)
finally:
  pass

query='select * from prueba'
cursorObj.execute(query)
rows = cursorObj.fetchall()
a1=list(rows)
a1=pd.DataFrame(rows)
a1

   0  1                2                                                  3
0  1  1          Bebidas              Gaseosas, café, té, cervezas y maltas
1  2  2      Condimentos  Salsas dulces y picantes, delicias, comida par...
2  3  3       Repostería                        Postres, dulces y pan dulce
3  4  4          Lácteos                                             Quesos
4  5  5  Granos/Cereales                    Pan, galletas, pasta y cereales
5  6  6           Carnes                                  Carnes preparadas
6  7  7  Frutas/Verduras                       Frutas secas y queso de soja
7  8  8  Pescado/Marisco                         Pescados, mariscos y algas

Insertar Valores en la tabla categorias

In [ ]:
sql="insert into categorias values(?,?,?,?)"
valores=(9,9,'xx','yy')
con.execute(sql, valores)

Verificar con un select en las tabla categorias

In [ ]:
query='select * from categorias'
cursorObj.execute(query)
rows = cursorObj.fetchall()
a1=list(rows)
a1=pd.DataFrame(rows)
a1

   0  1                2                                                  3
0  1  1          Bebidas              Gaseosas, café, té, cervezas y maltas
1  2  2      Condimentos  Salsas dulces y picantes, delicias, comida par...
2  3  3       Repostería                        Postres, dulces y pan dulce
3  4  4          Lácteos                                             Quesos
4  5  5  Granos/Cereales                    Pan, galletas, pasta y cereales
5  6  6           Carnes                                  Carnes preparadas
6  7  7  Frutas/Verduras                       Frutas secas y queso de soja
7  8  8  Pescado/Marisco                         Pescados, mariscos y algas
8  9  9               xx                                                 yy

Actualizar un registro

In [ ]:
sql="update categorias set nombrecategoria=?,descripcion=? where idcategoria=?"
valores=('Empacados','Materiales de plastico',9)
con.execute(sql, valores)

Crea la funcion Muestra

In [ ]:
def Muestra():
  query='select * from categorias'
  cursorObj.execute(query)
  rows = cursorObj.fetchall()
  a1=list(rows)
  a1=pd.DataFrame(rows)
  print(a1)
Muestra()

   0  1                2                                                  3
0  1  1          Bebidas              Gaseosas, café, té, cervezas y maltas
1  2  2      Condimentos  Salsas dulces y picantes, delicias, comida par...
2  3  3       Repostería                        Postres, dulces y pan dulce
3  4  4          Lácteos                                             Quesos
4  5  5  Granos/Cereales                    Pan, galletas, pasta y cereales
5  6  6           Carnes                                  Carnes preparadas
6  7  7  Frutas/Verduras                       Frutas secas y queso de soja
7  8  8  Pescado/Marisco                         Pescados, mariscos y algas
8  9  9               xx                                                 yy

Borrar un registro

In [ ]:
sql="delete from categorias where idcategoria=?"
valores=9
con.execute(sql,(valores,))
Muestra()

   0  1                2                                                  3
0  1  1          Bebidas              Gaseosas, café, té, cervezas y maltas
1  2  2      Condimentos  Salsas dulces y picantes, delicias, comida par...
2  3  3       Repostería                        Postres, dulces y pan dulce
3  4  4          Lácteos                                             Quesos
4  5  5  Granos/Cereales                    Pan, galletas, pasta y cereales
5  6  6           Carnes                                  Carnes preparadas
6  7  7  Frutas/Verduras                       Frutas secas y queso de soja
7  8  8  Pescado/Marisco                         Pescados, mariscos y algas

In [ ]:
def CRUDCategorias(Oper,Id=0,Nombre="",Des=""):
  if Oper=="I":
    sql="insert into categorias values(?,?,?,?)"
    valores=(Id,Id,Nombre,Des)
    con.execute(sql, valores)
    return
  if Oper=="L":
    query='select * from categorias'
    cursorObj.execute(query)
    rows = cursorObj.fetchall()
    a1=list(rows)
    a1=pd.DataFrame(rows)
    print(a1)
    return
  if Oper=="U":
    sql="update categorias set nombrecategoria=?,descripcion=? where idcategoria=?"
    valores=('Empacados','Materiales de plastico',Id)
    con.execute(sql, valores)
    return
  if Oper=="D":
    sql="delete from categorias where idcategoria=?"
    valores=Id
    con.execute(sql,(valores,))

CRUDCategorias(Oper="I",Id=10,Nombre='zz',Des='WW')
CRUDCategorias(Oper="L")
CRUDCategorias(Oper="U",Id=10,Nombre='Empaques',Des='Empaques de Plastico')
CRUDCategorias(Oper="L")
CRUDCategorias(Oper="D",Id=10)
CRUDCategorias(Oper="L")

    0   1                2                                                  3
0   1   1          Bebidas              Gaseosas, café, té, cervezas y maltas
1   2   2      Condimentos  Salsas dulces y picantes, delicias, comida par...
2   3   3       Repostería                        Postres, dulces y pan dulce
3   4   4          Lácteos                                             Quesos
4   5   5  Granos/Cereales                    Pan, galletas, pasta y cereales
5   6   6           Carnes                                  Carnes preparadas
6   7   7  Frutas/Verduras                       Frutas secas y queso de soja
7   8   8  Pescado/Marisco                         Pescados, mariscos y algas
8  10  10               zz                                                 WW
    0   1                2                                                  3
0   1   1          Bebidas              Gaseosas, café, té, cervezas y maltas
1   2   2      Condimentos  Salsas dulces y picantes, delicias, comida par...
2   3   3       Repostería                        Postres, dulces y pan dulce
3   4   4          Lácteos                                             Quesos
4   5   5  Granos/Cereales                    Pan, galletas, pasta y cereales
5   6   6           Carnes                                  Carnes preparadas
6   7   7  Frutas/Verduras                       Frutas secas y queso de soja
7   8   8  Pescado/Marisco                         Pescados, mariscos y algas
8  10  10        Empacados                             Materiales de plastico
   0  1                2                                                  3
0  1  1          Bebidas              Gaseosas, café, té, cervezas y maltas
1  2  2      Condimentos  Salsas dulces y picantes, delicias, comida par...
2  3  3       Repostería                        Postres, dulces y pan dulce
3  4  4          Lácteos                                             Quesos
4  5  5  Granos/Cereales                    Pan, galletas, pasta y cereales
5  6  6           Carnes                                  Carnes preparadas
6  7  7  Frutas/Verduras                       Frutas secas y queso de soja
7  8  8  Pescado/Marisco                         Pescados, mariscos y algas